// Package fix turns a comparison into a shell script that would make the
// second machine more like the first. hostdiff only prints the script; it
// never runs it. Everything taken from a snapshot is untrusted (it may come
// from another machine), so names are validated and single-quoted, and
// anything unusual is left out with a sanitised comment.
package fix

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/morass/hostdiff/internal/diff"
)

var (
	pkgRe     = regexp.MustCompile(`^[A-Za-z0-9@][A-Za-z0-9@._+/:-]{0,200}$`)
	digitsRe  = regexp.MustCompile(`^[0-9]{1,15}$`)
	domainRe  = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,200}$`)
	defKeyRe  = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9._ -]{0,200}$`)
	intRe     = regexp.MustCompile(`^-?[0-9]{1,18}$`)
	floatRe   = regexp.MustCompile(`^-?[0-9]{1,18}(\.[0-9]{1,18})?([eE][-+]?[0-9]{1,3})?$`)
	controlRe = regexp.MustCompile(`[\x00-\x1f\x7f]`)
)

// Quote single-quotes s for a POSIX shell.
func Quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// comment makes text safe inside a # comment: no newlines or control
// characters that could end the comment and start a command.
func comment(s string) string {
	s = controlRe.ReplaceAllString(s, "?")
	if len(s) > 160 {
		s = s[:160] + "…"
	}
	return s
}

type script struct {
	lines   []string
	skipped []string
}

func (sc *script) add(format string, args ...any) { sc.lines = append(sc.lines, fmt.Sprintf(format, args...)) }
func (sc *script) skip(kind, key, why string) {
	sc.skipped = append(sc.skipped, "# skipped "+comment(kind+" "+key)+": "+why)
}

// Script returns the commands, run on B, that bring over what only A has, and
// comments for the rest (removals and version differences are never
// automatic).
func Script(r *diff.Result) string {
	sc := &script{}
	a, b := comment(r.A.Label), comment(r.B.Label)
	sc.add("#!/bin/sh")
	sc.add("# Generated by hostdiff: run on %s to bring over what %s has.", b, a)
	sc.add("# Review every line first. Removals and upgrades are listed as comments only.")
	sc.add("set -e")
	for i := range r.Sections {
		s := &r.Sections[i]
		if !s.Comparable || s.Differences() == 0 {
			continue
		}
		start := len(sc.lines)
		for _, it := range s.OnlyA {
			install(sc, s.Kind, it.Key, it.Value, it.Tag)
		}
		for _, c := range s.Changed {
			change(sc, s.Kind, c)
		}
		for _, it := range s.OnlyB {
			if cmd := remove(s.Kind, it.Key); cmd != "" {
				sc.add("# only on %s: %s", b, cmd)
			}
		}
		if len(sc.lines) > start {
			sc.lines = append(sc.lines[:start], append([]string{"", "# " + comment(s.Title)}, sc.lines[start:]...)...)
		}
	}
	if len(sc.skipped) > 0 {
		sc.add("")
		sc.lines = append(sc.lines, sc.skipped...)
	}
	return strings.Join(sc.lines, "\n") + "\n"
}

func name(key, prefix string) (string, bool) {
	n, ok := strings.CutPrefix(key, prefix)
	return n, ok && pkgRe.MatchString(n)
}

func install(sc *script, kind, key, value, tag string) {
	prefixed := func(prefix, cmd string) bool {
		if !strings.HasPrefix(key, prefix) {
			return false
		}
		if n, ok := name(key, prefix); ok {
			sc.add(cmd, Quote(n))
		} else {
			sc.skip(kind, key, "unusual characters")
		}
		return true
	}
	switch kind {
	case "brew":
		if strings.HasPrefix(key, "formula › ") && tag == "dependency" {
			return // comes with whatever needs it
		}
		_ = prefixed("formula › ", "brew install %s") || prefixed("cask › ", "brew install --cask %s") || prefixed("tap › ", "brew tap %s")
	case "mas":
		id, ok := strings.CutPrefix(tag, "id ")
		if ok && digitsRe.MatchString(id) {
			sc.add("mas install %s  # %s", id, comment(key))
		} else {
			sc.skip(kind, key, "no App Store id")
		}
	case "packages":
		_ = prefixed("npm › ", "npm install -g %s") || prefixed("pipx › ", "pipx install %s") ||
			prefixed("uv › ", "uv tool install %s") || prefixed("cargo › ", "cargo install %s") ||
			prefixed("gh › ", "gh extension install %s")
	case "editors":
		_ = prefixed("vscode › ", "code --install-extension %s") || prefixed("cursor › ", "cursor --install-extension %s") ||
			prefixed("vscodium › ", "codium --install-extension %s")
	case "defaults":
		writeDefault(sc, key, value, tag)
	}
}

func change(sc *script, kind string, c diff.Change) {
	switch kind {
	case "defaults":
		writeDefault(sc, c.Key, c.A, c.TagA)
	case "brew", "mas", "packages", "editors", "apps":
		if c.TagA == "dependency" && c.TagB == "dependency" {
			return
		}
		sc.add("# version differs: %s is %s here, %s there", comment(c.Key), comment(c.B), comment(c.A))
	}
}

func remove(kind, key string) string {
	switch kind {
	case "brew":
		for prefix, cmd := range map[string]string{"formula › ": "brew uninstall ", "cask › ": "brew uninstall --cask ", "tap › ": "brew untap "} {
			if n, ok := name(key, prefix); ok {
				return cmd + Quote(n)
			}
		}
	case "packages":
		for prefix, cmd := range map[string]string{"npm › ": "npm uninstall -g ", "pipx › ": "pipx uninstall ", "uv › ": "uv tool uninstall ", "cargo › ": "cargo uninstall "} {
			if n, ok := name(key, prefix); ok {
				return cmd + Quote(n)
			}
		}
	case "editors":
		if n, ok := name(key, "vscode › "); ok {
			return "code --uninstall-extension " + Quote(n)
		}
	}
	return ""
}

// writeDefault emits `defaults write` for scalar settings whose domain and
// type were recorded by the collector.
func writeDefault(sc *script, key, value, detail string) {
	var domain, typ string
	for _, l := range strings.Split(detail, "\n") {
		if v, ok := strings.CutPrefix(l, "defaults "); ok {
			domain = v
		}
		if v, ok := strings.CutPrefix(l, "type "); ok {
			typ = v
		}
	}
	_, k, ok := strings.Cut(key, " › ")
	if !ok || domain == "" || typ == "" {
		sc.skip("defaults", key, "not a simple value")
		return
	}
	if !domainRe.MatchString(domain) || !defKeyRe.MatchString(k) {
		sc.skip("defaults", key, "unusual characters")
		return
	}
	var arg string
	switch typ {
	case "bool":
		if value != "true" && value != "false" {
			sc.skip("defaults", key, "not a boolean")
			return
		}
		arg = "-bool " + value
	case "int":
		if !intRe.MatchString(value) {
			sc.skip("defaults", key, "not an integer")
			return
		}
		arg = "-int " + value
	case "float":
		if !floatRe.MatchString(value) {
			sc.skip("defaults", key, "not a number")
			return
		}
		arg = "-float " + value
	case "string":
		if controlRe.MatchString(value) {
			sc.skip("defaults", key, "control characters")
			return
		}
		arg = "-string " + Quote(value)
	default:
		sc.skip("defaults", key, "unsupported type")
		return
	}
	sc.add("defaults write %s %s %s", Quote(domain), Quote(k), arg)
}
